export 'package:noronhaecotech/idiomas/arquivos_gerados/l10n.dart';
export 'package:flutter_localizations/flutter_localizations.dart';
export 'package:flutter_web_plugins/flutter_web_plugins.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:noronhaecotech/firebase_options.dart';
export 'package:cloud_firestore/cloud_firestore.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:flutter/foundation.dart';
export 'package:flutter/gestures.dart';
export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:crypto/crypto.dart';
export 'package:http/http.dart';
export 'dart:convert';
export 'dart:async';
export 'dart:math';
//////////////////////////////////////////////////////////////////////////////// Importes
export 'package:noronhaecotech/configuracoes/importar_sistemas.dart';
export 'package:noronhaecotech/configuracoes/importar_paginas.dart';
export 'package:noronhaecotech/configuracoes/importar_componentes.dart';
export 'package:noronhaecotech/configuracoes/importar_estilos.dart';
export 'package:noronhaecotech/configuracoes/importar_tipos.dart';
//////////////////////////////////////////////////////////////////////////////// Controladores
export 'package:noronhaecotech/importes/controladores/controlador_pagina.dart';
export 'package:noronhaecotech/importes/controladores/controlador_rolagem.dart';
export 'package:noronhaecotech/importes/controladores/controlador_celular.dart';
export 'package:noronhaecotech/importes/controladores/controlador_email.dart';
export 'package:noronhaecotech/importes/controladores/controlador_nome.dart';
export 'package:noronhaecotech/importes/controladores/controlador_senha.dart';
//////////////////////////////////////////////////////////////////////////////// Modelos
export 'package:noronhaecotech/importes/modelos/modelos_ddi.dart';
export 'package:noronhaecotech/importes/modelos/modelos_dialogo_sequencial.dart';
export 'package:noronhaecotech/importes/modelos/modelos_dispositivo.dart';
export 'package:noronhaecotech/importes/modelos/modelos_formatos_texto.dart';
export 'package:noronhaecotech/importes/modelos/modelos_objeto_selecao.dart';
export 'package:noronhaecotech/importes/modelos/modelos_paginas.dart';
export 'package:noronhaecotech/importes/modelos/modelos_validacao_senha.dart';
export 'package:noronhaecotech/importes/modelos/modelos_teclado.dart';
//////////////////////////////////////////////////////////////////////////////// Modelos Firebase
export 'package:noronhaecotech/importes/modelos/firebase/modelos_dados_usuarios.dart';
