name: noronhaecotech
description: by Noronha Designer.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.17.0

flutter_intl:
  enabled: true
  class_name: Idiomas
  main_locale: pt
  arb_dir: lib/idiomas
  output_dir: lib/idiomas/arquivos_gerados

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Orbitron-Regular
      fonts:
        - asset: assets/fontes/app/orbitron_regular.ttf
        - asset: assets/fontes/app/orbitron_medium.ttf
          weight: 500
        - asset: assets/fontes/app/orbitron_bold.ttf
          weight: 700
        - asset: assets/fontes/app/orbitron_black.ttf
          weight: 900