// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKOvAC1bU2IBWLJHzAn8MpH7fHyvTTK9Q',
    appId: '1:1068583295934:web:768f16b3a66164f4c437ef',
    messagingSenderId: '1068583295934',
    projectId: 'noronha-ecotech',
    authDomain: 'noronha-ecotech.firebaseapp.com',
    storageBucket: 'noronha-ecotech.appspot.com',
    measurementId: 'G-6GYD80ZK5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgp-1SdSNu2fIa2sXkKzmGrhpzm3dLWFY',
    appId: '1:1068583295934:android:e43bc3dd16dc0c0ac437ef',
    messagingSenderId: '1068583295934',
    projectId: 'noronha-ecotech',
    storageBucket: 'noronha-ecotech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJhDsqcUSlO92IfctJBMgBp4rXza7uFNo',
    appId: '1:1068583295934:ios:ee68df5fcc38fe43c437ef',
    messagingSenderId: '1068583295934',
    projectId: 'noronha-ecotech',
    storageBucket: 'noronha-ecotech.appspot.com',
    iosClientId: '1068583295934-9fb9rtad742eg4bvsrbk3v4qbkhe3kes.apps.googleusercontent.com',
    iosBundleId: 'com.noronhadesigner.noronhaecotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJhDsqcUSlO92IfctJBMgBp4rXza7uFNo',
    appId: '1:1068583295934:ios:ee68df5fcc38fe43c437ef',
    messagingSenderId: '1068583295934',
    projectId: 'noronha-ecotech',
    storageBucket: 'noronha-ecotech.appspot.com',
    iosClientId: '1068583295934-9fb9rtad742eg4bvsrbk3v4qbkhe3kes.apps.googleusercontent.com',
    iosBundleId: 'com.noronhadesigner.noronhaecotech',
  );
}
